### ISSUE TITLE
[BUG] Animals & mobs spawning

### ISSUE THREAD

**Issue by Sotlol1** [NikV2/ResourceWorld#1]
**Describe the bug**
Animals & mobs spawn despite "disable_entity_spawning" being set to true and spawning properties being set to "0"

**To Reproduce**
1. Go to 'config.yml'
2. Change 'change disable_entity_spawning' to true
3. Restart the server.
4. Animals & mobs will still spawn

**Expected behavior**
Mobs & animals should not spawn.

**Server Version - Plugin Version**
Server version:  Paper 129 (1.16.1)
Plugin Version:  1.7.6

Additional information:
I tried to reset the world as well but they just spawned anyhow.

**Comment by NikV2** [comment]
This config option prevents new mobs from spawning but it does not affect the ones that were already spawned while the world generated, Do you think it should be better if i make it clear all the entities on a world reset and Then prevent them from spawning?

**Comment by Sotlol1** [comment]
Like i said in the additional information they spawn despite resetting the world.

**Comment by Sotlol1** [comment]
Yeah, I think that would be better :)
