### ISSUE TITLE
[19:35:11 ERROR]: Could not pass event PlayerQuitEvent to ResourceWorld v1.9.3

### ISSUE THREAD

**Issue by wattywatty14** [NikV2/ResourceWorld#11]
This happens every time I quit my server:
https://pastebin.com/8xz7KT0T

**Comment by NikV2** [comment]
Do a complete reset on your config.yml, or try to manually put your main world in the main_world section. let me know if that fixes it.

**Comment by wattywatty14** [comment]
I did both. it doesn't solve the issue.

**Comment by NikV2** [comment]
Sorry i'm not able to reproduce the error, Make sure there are no typos inside the config. I'll close this issue for now.
