### ISSUE TITLE
[REQUEST] Certain parts of the world to NOT be reset

### ISSUE THREAD

**Issue by larssieboy18** [NikV2/ResourceWorld#13]
**What feature would you like to be added and why?**
It would be really cool if it could be possible to not reset certain parts of the world, for example the spawn. This might be possible by ignoring certain region files (if that is how the plugin works, not sure). Server owners would have to do some calculations, but there are converters that can be found online, so shouldn't be that hard.

**Comment by NikV2** [comment]
That would require a lot of work or possibly a massive re-code, So i'll have to deny this request for the time being.

You might want to look for an Alternative like Regionerator which does exactly what you mention.
