### ISSUE TITLE
[BUG] Config File Generated from Plugin doesn't contain  #Entity Spawning Properties

### ISSUE THREAD

**Issue by Zefferis** [NikV2/ResourceWorld#14]
**Describe the bug**
When generating the config file from the plugin itself rather than updating an existing config.yml, the config settings for  # Entity Spawning Properties are missing for all 3 worlds.

**To Reproduce**
Generate a new config file using RW v1.9.4

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Paper 1.16.5 / build 470

**Comment by NikV2** [comment]
These settings were removed from a recent update, I forgot to remove them from the wiki config, Woops!
