### ISSUE TITLE
Wrong operator in PlayerPortalEvent while respecting vanilla ratio

### ISSUE THREAD

**Issue by hohoaisan** [NikV2/ResourceWorld#16]
https://github.com/NikV2/ResourceWorld/blob/64cf1c343911aa8e79c580d0cead5ae0b95f3f93/src/main/java/me/nik/resourceworld/modules/impl/portals/PortalNether.java#L30

It is supposed to be / (divide) rather than % (modulus) operator, right?

And I have looked at the onPortalNether event and the Plugin was not *8 each X Y and Z, it should be like this:
```
Location from = e.getFrom();
        if (Config.Setting.NETHER_PORTALS_VANILLA_RATIO.getBoolean()) {
            e.setTo(new Location(Bukkit.getWorld(Config.Setting.NETHER_PORTALS_PORTALWORLD.getString()), from.getX()*8, from.getY()*8, from.getZ()*8));
        } else {
            e.setTo(new Location(Bukkit.getWorld(Config.Setting.NETHER_PORTALS_PORTALWORLD.getString()), from.getX(), from.getY(), from.getZ()));
        }
```

**Comment by hohoaisan** [comment]
I edited and tested on my MC server and the issue (wrong portal creation coordinate - that I mentioned before in Discord) is gone.

**Comment by NikV2** [comment]
I'll have it changed, thanks for letting me know!
