### ISSUE TITLE
[REQUEST] Generator support

### ISSUE THREAD

**Issue by Ghost-chu** [NikV2/ResourceWorld#17]
**What feature would you like to be added and why?**
I want to use a custom generator for the resources world, cause it optimized for resources and looks really good.

**Comment by 24Marzo** [comment]
He isnt working much on resource world these days

**Comment by NikV2** [comment]
Hello, certain generators like RWG support plugins like this one by simply putting the world name in the config.

I don't know how to support external world generators since im pretty sure they should be the ones handling any world generation.
