### ISSUE TITLE
[REQUEST] Placeholder Updates

### ISSUE THREAD

**Issue by xXQiuChenXx** [NikV2/ResourceWorld#20]
I have used the placeholder %rw_world% but it is too long. I suggest to make a formatted placeholder and make it able to translate . That would be shorter, easy for the scoreboard and holograms.
![2021-07-21_16 57 26](https://user-images.githubusercontent.com/51996408/126462309-1939167a-d135-41cd-a5fd-6602059c46d7.png)

**Comment by NikV2** [comment]
You can change it inside the config.yml file

```yaml
  # Sets the format of the remaining time.
  reset_format: '%days% days %hours% hours %minutes% minutes %seconds% seconds'```
