### ISSUE TITLE
[ERROR] Chunk loading errors after the world reset causing the server in locked state forever

### ISSUE THREAD

**Issue by Akiranya** [NikV2/ResourceWorld#21]
**Error(s)**
https://pastebin.ubuntu.com/p/kzyyjnrKY4/

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
This server is running Purpur version git-Purpur-1331 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 635d108 on ver/1.17.1)

**Additional Information (Optional)**
The first plugin appeared in the watch dog warnings is `me.olipulse.rainbowspro.rainbows` which spawns random rainbow in the resource world at certain interval. Also there are other plugins appeared in the warnings. I guess it needs to load a chunk in order to spawn the rainbow somehow but I'm not quite sure if it's RainbowPro causing the problem or it's ResourceWorld. I'll report this issue to the dev of RainbowPro as well.

**Comment by NikV2** [comment]
Let me know if this is resolved as i can not see the paste you've published.
