### ISSUE TITLE
[BUG] Placeholders are not showing left over time.

### ISSUE THREAD

**Issue by Skizzles** [NikV2/ResourceWorld#24]
**Describe the bug**
For some reason my placeholders are not working correctly.

**To Reproduce**
Unsure

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Purpur 1.17.1

**Additional Information (Optional)**
N/A
![FozunERi33](https://user-images.githubusercontent.com/30563757/142217339-f19a9747-a806-4dcc-b877-8e2f3c422f88.png)

**Comment by NikV2** [comment]
Did you reload? or did this happen after a world reset?
