### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by ms0ur** [NikV2/ResourceWorld#26]
**Error(s)**
[Provide a Pastebin link with your error.](https://pastebin.com/R1Wu2jYY)

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Current: git-Purpur-1613 (MC: 1.18.2)

**Additional Information (Optional)**
when executing the command for the first time, everything works, after that the command does not work
After some time passes (approximately 3-5 minutes), everything works again

**Comment by NikV2** [comment]
I can't reproduce, are you sure you didn't reload anything?
And which command exactly?

**Comment by ms0ur** [comment]
> I can't reproduce, are you sure you didn't reload anything? And which command exactly?

I'm sure I didn't use /reload. I am running the /rw tp command. I do not know how, but the problem solved itself. Anyway, thanks for the help.

**Comment by NikV2** [comment]
Make sure you're on the latest version, i fixed a lot of stuff in the latest update.
