### ISSUE TITLE
All Nether Portals Go to the Resource_End [BUG]

### ISSUE THREAD

**Issue by BellaIngenue** [NikV2/ResourceWorld#29]
**Describe the bug**
All Nether Portals (In both the normal AND resource world) direct you to a random spot in the Resource_End. This is done with modification of the default config. Otherwise all Nether Portals bring you to the Regular Nether. 

**To Reproduce**
This bug does not persist on the default config. But I have been using my modified config for years now and no issues. 
Problem started with ResourceWorld-1.9.5.jar but continue with the most recent jar file as well

1. Download ResourceWorld-1.9.5.jar or later
2. Modify Config.yml to allow Nether Portals in all worlds to go to the Resource_Nether
3. To Clarify: I made the Resource_Nether override: true (Even with other modifications of this config.yml, it still seems to bring the player to the Resource_End. I also tried disabling the Resource_End but it would continue to remake it) 
4. Go to either the Normal World or the Resource_World
5. Create a Nether Portal and Step in
6. You should be somewhere random in the Resource_End

I even tried reproducing with a local server and the same issues surfaced. I'm just not sure what to do and would appreciate any help or guidance. 
**Does the issue still persist on the default config?**
No

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Paper 1.18.1 version 216

**Additional Information (Optional)**
I love this plugin but I just can't figure out how to get it to work again the way I would like. Thank you so much for all your hard work!!

**Comment by Izibane** [comment]
![FKGbEEji](https://user-images.githubusercontent.com/77923336/169317511-acaa3729-5dbb-4b70-9746-a89183dfcf72.gif)

**Comment by NikV2** [comment]
Hi there! I'm currently in the military again so i'm not able to test it in-game myself. Could you try by updating to the latest version and making a clean fresh config?

**Comment by VimaMT** [comment]
I'm using the latest version, and I am seeing the same issue. Nether Portals created in the main world are sending players to the Resource End. It generates a platform out of obsidian with part of a portal around it.

**Comment by VimaMT** [comment]
From your module PortalNether.java:

World world = Bukkit.getWorld(Config.Setting.END_NAME.getString());

**Comment by Izibane** [comment]
Average Nik moment

**Comment by FancyBelt798245** [comment]
although im having the same problem i still love this plugin

**Comment by crimsson** [comment]
> although im having the same problem i still love this plugin, honestly cant wait for a fix!
> 
> I fixed it if anyone wants the updated code

when you said you fixed it, does that mean the portal is working properly?
would you mind sharing the updated code?

**Comment by FancyBelt798245** [comment]
> > although im having the same problem i still love this plugin, honestly cant wait for a fix!
> > I fixed it if anyone wants the updated code
> 
> when you said you fixed it, does that mean the portal is working properly? would you mind sharing the updated code?

yes, i have fixed it & tested it on my server if can provide you with the file. The code i modified was in the Nether module, the code made it so the player was sent to the Resource_End so all i had to do is change the to Resource_Nether and compile the code and bam fixed! My config file and the modifed jar file are attached (;

[Attached Files.zip](https://github.com/NikV2/ResourceWorld/files/10053773/Attached.Files.zip)
