### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ArtamaMeyer** [NikV2/ResourceWorld#3]
**Describe the bug**
Players can not pickup items after a world reset

**To Reproduce**
reset the world via command

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
paper 251 1.16.3

**Additional Information (Optional)**
Fixed after server restart, Why does that happen?

**Comment by NikV2** [comment]
I can't seem to be able to reproduce, Tried using the latest version of Paper.

Make sure your Paper is up to date. The plugin does not listen for any events related to that so i'm guessing it was a Spigot bug on the version u were using.

**Comment by NikV2** [comment]
Alternatively, try looking if any plugin is interfering with it.
