### ISSUE TITLE
[Question/Enhancement Request]

### ISSUE THREAD

**Issue by TheDarthFather** [NikV2/ResourceWorld#31]
Hello,
Is there any way I can use this with a world generation plugin (eg Terra) or a world customisation datapack like terralith? 

PS: It will be super-cool, as this world can be used not only for resource, but as main hunting/play world. In this was you can benefit from world generation customisations .. as on your main one you cant regenerate chunks ... because of the player buildings.

**Comment by NikV2** [comment]
Sorry but i dont think ill be adding that
