### ISSUE TITLE
Bug? Error? 

### ISSUE THREAD

**Issue by MBskiii** [NikV2/ResourceWorld#36]
So I'm not sure if this is a bug or something on my end or if I enabled something I wasn't supposed to. So I have a resource world for Overworld, nether, & end. The file size of the Overworld & end stay the same unless I load some chunks. But the nether file size constantly goes up whether I'm in the world or not. Even after I reset the world and I don't even load the chunks, the file size still goes up. So like I said, I'm not sure if this is a bug, error, or something I did.

**Comment by NikV2** [comment]
I think thats how the worlds work in general
