### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Banexplain** [NikV2/ResourceWorld#37]
**Error(s)**
https://discord.com/channels/687445122723610678/687445122723610684/1042110448595644478 | [error.txt](https://github.com/NikV2/ResourceWorld/files/10050692/error.txt)
https://discord.com/channels/687445122723610678/687445122723610684/1042120313682546770 | [message.txt](https://github.com/NikV2/ResourceWorld/files/10050693/message.txt)

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Your server software (Latest Paper 1.19.2 Build)

**Additional Information (Optional)**
The Plugin does not work at all.

Sometimes the Plugin Crashes the complete Server than a Player want's to join or the Plugin crashes the Server by entering a Plugin specific command (/resource tp) - hope that you could fix this soon.

Best regards
BanExplain | Eric

**Comment by NikV2** [comment]
Try updating the plugin + Paper
