### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by crimsson** [NikV2/ResourceWorld#38]
**Describe the bug**
Hi, so im having big issues regarding this plugin, that the RAM usage and CPU usage rapidly goes up. When using default config, there was no issue. However, when I enable resource world for Nether and End, the RAM and CPU usage starts going up (until my server restart itself due to ram limit on my host). Note that this plugin worked just fine on older server like Paper 1.16.5.
So I'm not sure if this is a bug or something on my end or if I enabled something I wasn't supposed to.

**To Reproduce**
- Install ResourceWorld-1.9.8
- Enable nether and/or end resource in config, and then restart
- Restart the server, and then watch the RAM and CPU usage meter going up suddenly

**Does the issue still persist on the default config?**
No

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Paper 1.19.2 #271

**Additional Information (Optional)**
if you need more info from me, i can provide it later.

**Comment by NikV2** [comment]
World creation is very heavy especially in the latest versions, u should re-generate the world on every restart
