### ISSUE TITLE
[ERROR] I'm getting an issue when I type /rw reset

### ISSUE THREAD

**Issue by ToxicWaterOP** [NikV2/ResourceWorld#42]
**Error(s)**
[Provide a Pastebin link with your error.](https://pastebin.com/FPXuQ3TA)

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Your server software (ie Paper 1.19.2)

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Make sure to define the resource world name in the config.yml, something's wrong with the config's world name

**Comment by NikV2** [comment]
Or the world doesn't exist
