### ISSUE TITLE
[BUG] Geyser/Bedrock users get teleported to 0,0 in resource world

### ISSUE THREAD

**Issue by HorusApl** [NikV2/ResourceWorld#45]
**Describe the bug**
Whenever a Bedrock user is exploring the resource world, they will at random get teleported to 0,0 in the resource world. Issue doesn't happen in main world.

**To Reproduce**
Use any mobile Bedrock and try to explore the resource world

**Does the issue still persist on the default config?**
Yes

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Your server software (ie Paper 1.12.2)

**Additional Information (Optional)**

**Comment by NikV2** [comment]
Can't reproduce cause i dont have bedrock
Try updating the bedrock thingies or even the server jar, no idea why it does that
