### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by SpigotWorkspace** [NikV2/ResourceWorld#6]
I would like a function where you can change the format of the duration string.

I can also do it in my fork and then make a PR.

It's pretty simple compared to what you have already done, you can do it :D

With kind regards

SpigotWorkspace | Florian

**Comment by NikV2** [comment]
I apologize for my absence, i'm quite busy these weeks. So if you need this feature right now i'd recommend u make a PR if possible, just so u won't have to wait for me to implement it!
