### ISSUE TITLE
[SUGGESTION] Make configs not reset when an error occurs

### ISSUE THREAD

**Issue by larssieboy18** [NikV2/ResourceWorld#8]
**Describe the bug**
The config file resets when there is an error.

**To Reproduce**
Steps to reproduce the behavior.
Put a random letter in an empty line to create an error, after reload of the plugin or restart of the server, the config is completely reset.

**Does the issue still persist on the default config?**
No

**Is the plugin up to date?**
Yes

**Server Environment & Version**
Your server software (ie Paper 1.12.2)
Tuinity 1.16.4

**Additional Information (Optional)**
In my opinion, the best way to tackle this is to have the plugin disable itself when it detects an error and tell the user where the error is to prevent resetting all custom settings.

**Comment by NikV2** [comment]
I might implement it in the future, Since i don't want to completely add a try catch to the whole method that loads the files. It's inneficient and it wont show the actual problem. I might look into it in the future and make it so it lets u know which part of the file has the issue and disable
